# Example configuration file (save as config.yaml)

database:
  path: "karaoke_videos.db"
  backup_enabled: true
  backup_retention_days: 7
  backup_interval_hours: 24
  vacuum_threshold_mb: 100
  connection_pool_size: 10  # For high-concurrency operations
  connection_timeout: 30.0

scraping:
  max_concurrent_workers: 3  # Reduced for better API compliance
  max_retries: 3
  timeout_seconds: 60  # Increased for large playlists/4K results
  rate_limit_per_hour: 3600  # Conservative rate limiting
  min_request_interval: 1.0  # Seconds between requests

search:
  primary_method: "yt_dlp"
  max_results_per_query: 100

data_sources:
  ryd_api_enabled: true
  ryd_timeout: 10
  ryd_confidence_threshold: 0.1
  musicbrainz_enabled: true
  musicbrainz_timeout: 5

logging:
  level: "INFO"
  file_path: "karaoke_collector.log"
  console_output: true

ui:
  show_progress_bar: true
  save_thumbnails: false

# Runtime settings
incremental_mode: true
skip_existing: true
dry_run: false